apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: zulu25-service

resources:
  - deployment.yaml
  - service.yaml
  - poddisruptionbudget.yaml

# Point at your registry / tag, or let Flux's image automation patch it here.
images:
  - name: ghcr.io/egkristi/zulu25-service
    newTag: 1.0.0-SNAPSHOT
