apiVersion: v1
kind: Service
metadata:
  name: zulu25-service
  labels:
    app.kubernetes.io/name: zulu25-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: zulu25-service
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
